---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: speedtest-ap
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: speedtest-ap
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: speedtest-ap
    spec:
      containers:
      - name: speedtest-ap
        image: yuma1315/speedtest-k8s:latest
        imagePullPolicy: Always
        env:
          # Use secret in real usage
        - name: DB_HOST
          value: mysql-tmp0
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: password
        - name: DB_DATABASE
          value: speedtest
        ports:
        - name: http
          containerPort: 80
                #- containerPort: 80
                #name: speedtest-ap

---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-ap
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: speedtest-ap
  type: LoadBalancer
